const indexes = {
    0: "NORMAL",
    1: "FIRE",
    2: "WATER",
    3: "ELECTRIC",
    4: "GRASS",
    5: "ICE",
    6: "FIGHTING",
    7: "POISON",
    8: "GROUND",
    9: "FLYING",
    10: "PSYCHIC",
    11: "BUG",
    12: "ROCK",
    13: "GHOST",
    14: "DRAGON",
    15: "DARK",
    16: "STEEL",
    17: "FAIRY",
    18: "KANTO",
    19: "JOHTO",
    20: "HOENN",
    21: "SINNOH",
    22: "UNOVA",
    23: "KALOS",
    24: "ALOLA",
    25: "GALAR",
    26: "PALDEA",
    27: "HISUI",
    28: "LEGENDARY",
    29: "MYTHIC",
    30: "ULTRABEAST",
    31: "BABY",
    32: "FOSSIL",
    33: "PARADOX",
    34: "STARTER",
    35: "MEGA",
    36: "MONOTYPE",
    37: "DUALTYPE",
};

const imagensDosTipos = {
    NORMAL: `https://archives.bulbagarden.net/media/upload/0/08/NormalIC_SV.png`,
    FIRE: `https://archives.bulbagarden.net/media/upload/a/a2/FireIC_SV.png`,
    WATER: `https://archives.bulbagarden.net/media/upload/d/de/WaterIC_SV.png`,
    ELECTRIC: `https://archives.bulbagarden.net/media/upload/7/77/ElectricIC_SV.png`,
    GRASS: `https://archives.bulbagarden.net/media/upload/7/7b/GrassIC_SV.png`,
    ICE: `https://archives.bulbagarden.net/media/upload/1/13/IceIC_SV.png`,
    FIGHTING: `https://archives.bulbagarden.net/media/upload/0/0f/FightingIC_SV.png`,
    POISON: `https://archives.bulbagarden.net/media/upload/9/9d/PoisonIC_SV.png`,
    GROUND: `https://archives.bulbagarden.net/media/upload/f/f8/GroundIC_SV.png`,
    FLYING: `https://archives.bulbagarden.net/media/upload/d/d7/FlyingIC_SV.png`,
    PSYCHIC: `https://archives.bulbagarden.net/media/upload/9/96/PsychicIC_SV.png`,
    BUG: `https://archives.bulbagarden.net/media/upload/d/d1/BugIC_SV.png`,
    ROCK: `https://archives.bulbagarden.net/media/upload/3/32/RockIC_SV.png`,
    GHOST: `https://archives.bulbagarden.net/media/upload/2/2c/GhostIC_SV.png`,
    DRAGON: `https://archives.bulbagarden.net/media/upload/7/7f/DragonIC_SV.png`,
    DARK: `https://archives.bulbagarden.net/media/upload/3/30/DarkIC_SV.png`,
    STEEL: `https://archives.bulbagarden.net/media/upload/b/b8/SteelIC_SV.png`,
    FAIRY: `https://archives.bulbagarden.net/media/upload/c/c6/FairyIC_SV.png`
};

const infosDoJogo = {
    "pokedoku-2x2": {
        rows: 2,
        cols: 2,
        min_tentativas: 4,
        limite_modo_dificil: 4,
        permissividade_modo_dificil: 1,
    },
    "pokedoku-3x3": {
        rows: 3,
        cols: 3,
        min_tentativas: 9,
        limite_modo_dificil: 5,
        permissividade_modo_dificil: 3,
    },
    "pokedoku-4x4": {
        rows: 4,
        cols: 4,
        min_tentativas: 16,
        limite_modo_dificil: 1,
        permissividade_modo_dificil: 5,
    },
    "pokedoku-single": {
        rows: 3,
        cols: 3,
        min_tentativas: 1,
    },
}